"toyotacsv"
import pandas as pd
import numpy as np
carsdata=pd.read_csv("D:\Python\datacooking\Toyota\Toyota.csv",index_col=0,na_values=["??","????"])
print(carsdata)
shallow=carsdata.copy(deep=False)
deep=carsdata.copy(deep=True)
carsdata.index
carsdata.columns
carsdata.size
carsdata.shape
carsdata.memory_usage()
carsdata.ndim
carsdata.head(7)
carsdata.tail(7)
carsdata.at[107,'KM']
carsdata.iat[107,2]
fueltype=carsdata.loc[:,'FuelType']
det1=carsdata.loc[107,:]
carsdata.dtypes
#carsdata.get_dtype_counts()
carsdata.dtypes.value_counts()
carsdata.select_dtypes(exclude=int)
carsdata.select_dtypes(include=[float,int])
carsdata.select_dtypes(object)
carsdata.info()
print(np.unique(carsdata['Doors']))
print(len(carsdata['KM']))
print(len(list(np.unique(carsdata['KM']))))
x=np.unique(carsdata['MetColor'])
print(x,len(carsdata['MetColor']))
print(carsdata['Automatic'].dtype)
carsdata['Automatic']=carsdata['Automatic'].astype(object)
carsdata['MetColor']=carsdata['MetColor'].astype(object)
print(carsdata['Automatic'].dtype)
carsdata.info()
carsdata['FuelType'].nbytes
carsdata['FuelType'].astype('category').nbytes
carsdata.info()
carsdata['Doors'].astype('category')
carsdata['FuelType'].astype('category')
print(np.unique(carsdata['Doors']))
carsdata['Doors'].replace('three',3,inplace=True)
carsdata['Doors'].replace('four',4,inplace=True)
carsdata['Doors'].replace('five',5,inplace=True)
carsdata['Doors'].astype('category')
carsdata['Doors']=carsdata['Doors'].astype('int64')
print(np.unique(carsdata['Doors']))
carsdata.isnull().sum()